-- Seed: the full Canadian transit-agency census beyond the 10 launch agencies.
-- Sourced from open/public sources (Wikipedia "List of transit agencies in Canada",
-- municipal/provincial transit sites, transit.land / Mobility Database GTFS registries).
-- The restricted CUTA member directory was NOT used. Compiled + independently verified
-- by a research fan-out on 2026-05-31. service_area_population is left NULL (NOT
-- fabricated); fiscal_year_end_month defaults to 12 (the municipal calendar year — the
-- known non-calendar provincial exceptions, BC Transit + Metrolinx, are in the launch 10).
-- Re-runnable (ON CONFLICT (slug) DO NOTHING). Keeps the existing 10 untouched.
-- agency_modes is seeded to exactly match each row's primary_modes (seed test #3).
SET client_encoding = 'UTF8';

INSERT INTO core.agencies (slug, legal_name, short_name, country, subdivision, fiscal_year_end_month, currency, primary_modes) VALUES
  ('airdrie-transit', 'Airdrie Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('beaumont-transit', 'Beaumont Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('camrose-transit', 'Camrose Community Bus', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('cochrane-colt', 'Cochrane On-demand Local Transit (COLT)', 'COLT', 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('cold-lake-transit', 'Cold Lake Transit', 'CLT', 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('fort-saskatchewan-transit', 'Fort Saskatchewan Transit', 'Fort Sask Transit', 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('grande-prairie-transit', 'Grande Prairie Transit', 'GP Transit', 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('hinton-transit', 'Hinton Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('leduc-transit', 'Leduc Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('lethbridge-transit', 'Lethbridge Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('medicine-hat-transit', 'Medicine Hat Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('okotoks-transit', 'Okotoks Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('red-deer-county-transit', 'Red Deer County Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('red-deer-transit', 'Red Deer Transit', 'RDT', 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('roam-transit', 'Bow Valley Regional Transit Services Commission (Roam Transit)', 'Roam', 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('spruce-grove-transit', 'Spruce Grove Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('st-albert-transit', 'St. Albert Transit', 'StAT', 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('strathcona-county-transit', 'Strathcona County Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('whitecourt-transit', 'Whitecourt Transit', NULL, 'CA', 'AB', 12, 'CAD', ARRAY['bus']),
  ('wood-buffalo-transit', 'RMWB Transit (Wood Buffalo Transit)', 'RMWB Transit', 'CA', 'AB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('west-vancouver-blue-bus', 'West Vancouver Blue Bus', 'Blue Bus', 'CA', 'BC', 12, 'CAD', ARRAY['bus']),
  ('brandon-transit', 'Brandon Transit', 'Brandon Transit', 'CA', 'MB', 12, 'CAD', ARRAY['bus']),
  ('flin-flon-transit', 'Flin Flon Transit', 'Flin Flon Transit', 'CA', 'MB', 12, 'CAD', ARRAY['bus']),
  ('selkirk-transit', 'Selkirk Transit', 'Selkirk Transit Authority', 'CA', 'MB', 12, 'CAD', ARRAY['bus']),
  ('winkler-transit', 'Winkler On-Demand Transit', 'Winkler On-Demand Transit', 'CA', 'MB', 12, 'CAD', ARRAY['on_demand']),
  ('winnipeg-transit', 'Winnipeg Transit', 'Winnipeg Transit', 'CA', 'MB', 12, 'CAD', ARRAY['bus','brt']),
  ('acadian-peninsula-flexi', 'Flexi Mobilite rurale (Acadian Peninsula Community Transportation)', 'Flexi', 'CA', 'NB', 12, 'CAD', ARRAY['bus']),
  ('bathurst-flexgo', 'FlexGo Bathurst (Chaleur Regional Service Commission)', 'FlexGo Bathurst', 'CA', 'NB', 12, 'CAD', ARRAY['on_demand']),
  ('codiac-transpo', 'Codiac Transpo (Codiac Transit Commission)', 'Codiac Transpo', 'CA', 'NB', 12, 'CAD', ARRAY['bus']),
  ('edmundston-flexgo', 'FlexGo (Edmundston regional transit)', 'FlexGo', 'CA', 'NB', 12, 'CAD', ARRAY['bus','on_demand']),
  ('fredericton-transit', 'Fredericton Transit', 'Fredericton Transit', 'CA', 'NB', 12, 'CAD', ARRAY['bus']),
  ('miramichi-transit', 'Miramichi Transit (Miramichi Public Transit Commission Inc.)', 'Miramichi Transit', 'CA', 'NB', 12, 'CAD', ARRAY['bus']),
  ('saint-john-transit', 'Saint John Transit', 'Saint John Transit', 'CA', 'NB', 12, 'CAD', ARRAY['bus']),
  ('corner-brook-transit', 'Corner Brook Transit (City of Corner Brook)', 'Corner Brook Transit', 'CA', 'NL', 12, 'CAD', ARRAY['bus','on_demand']),
  ('happy-valley-goose-bay-transit', 'Happy Valley-Goose Bay On-Demand Bus Service', 'HVGB Transit', 'CA', 'NL', 12, 'CAD', ARRAY['on_demand']),
  ('metrobus-st-johns', 'Metrobus Transit (St. John''s Transportation Commission)', 'Metrobus', 'CA', 'NL', 12, 'CAD', ARRAY['bus']),
  ('antigonish-transit', 'Antigonish Community Transit Society', 'Antigonish Community Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus','on_demand']),
  ('bayrides', 'BayRides (St. Margaret''s Bay Community Transportation Society)', 'BayRides', 'CA', 'NS', 12, 'CAD', ARRAY['on_demand']),
  ('bridgewater-transit', 'Bridgewater Transit', 'Bridgewater Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus']),
  ('cape-breton-transit', 'Transit Cape Breton', 'Transit Cape Breton', 'CA', 'NS', 12, 'CAD', ARRAY['bus']),
  ('east-hants-rider', 'East Hants Community Rider', 'East Hants Community Rider', 'CA', 'NS', 12, 'CAD', ARRAY['on_demand']),
  ('halifax-transit', 'Halifax Transit', 'Halifax Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus','ferry']),
  ('musgo-rider', 'MusGo Rider Co-operative Ltd.', 'MusGo Rider', 'CA', 'NS', 12, 'CAD', ARRAY['on_demand']),
  ('pictou-county-transit', 'Pictou County Transit', 'Pictou County Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus']),
  ('strait-area-transit', 'Strait Area Transit Co-operative Ltd.', 'Strait Area Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus','on_demand']),
  ('tidal-transit', 'Tidal Transit (formerly Kings Transit Authority)', 'Tidal Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus']),
  ('yarmouth-transit', 'Yarmouth Transit (Town of Yarmouth)', 'Yarmouth Transit', 'CA', 'NS', 12, 'CAD', ARRAY['bus']),
  ('yellowknife-transit', 'YKTransit (Yellowknife Transit)', 'YKTransit', 'CA', 'NT', 12, 'CAD', ARRAY['bus','paratransit']),
  ('barrie-transit', 'Barrie Transit', 'Barrie Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('belleville-transit', 'Belleville Transit', 'Belleville Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('brampton-transit', 'Brampton Transit', 'Brampton Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus','brt']),
  ('brantford-transit', 'Brantford Transit', 'Brantford Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('brockville-transit', 'Brockville Transit', 'Brockville Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('bwg-transit', 'BWG Transit', 'BWG Transit', 'CA', 'ON', 12, 'CAD', ARRAY['on_demand']),
  ('chatham-kent-transit', 'Chatham-Kent Transit (Ride CK)', 'CK Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('cobourg-transit', 'Cobourg Transit', 'Cobourg Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus','on_demand']),
  ('collingwood-transit', 'Collingwood Transit (Colltrans)', 'Colltrans', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('cornwall-transit', 'Cornwall Transit', 'Cornwall Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('durham-region-transit', 'Durham Region Transit', 'DRT', 'CA', 'ON', 12, 'CAD', ARRAY['bus','on_demand']),
  ('elliot-lake-transit', 'Elliot Lake Transit', 'Elliot Lake Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('grand-river-transit', 'Grand River Transit', 'GRT', 'CA', 'ON', 12, 'CAD', ARRAY['bus','light_rail']),
  ('greater-sudbury-transit', 'Greater Sudbury Transit (GOVA)', 'GOVA', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('guelph-transit', 'Guelph Transit', 'Guelph Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('hamilton-street-railway', 'Hamilton Street Railway', 'HSR', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('huntsville-transit', 'Huntsville Transit', 'Huntsville Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('kenora-transit', 'Kenora Transit', 'Kenora Transit', 'CA', 'ON', 12, 'CAD', ARRAY['on_demand']),
  ('kingston-transit', 'Kingston Transit', 'Kingston Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('leamington-transit', 'Leamington Transit (LT-GO)', 'LT-GO', 'CA', 'ON', 12, 'CAD', ARRAY['on_demand']),
  ('lindsay-transit', 'Lindsay Transit', 'Lindsay Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('london-transit', 'London Transit Commission', 'London Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('midland-penetanguishene-transit', 'Midland Penetanguishene Transit', 'Mid-Pen Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('milton-transit', 'Milton Transit', 'Milton Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus','on_demand']),
  ('niagara-transit', 'Niagara Transit Commission', 'Niagara Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('north-bay-transit', 'North Bay Transit', 'North Bay Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('oakville-transit', 'Oakville Transit', 'Oakville Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus','on_demand']),
  ('orangeville-transit', 'Orangeville Transit', 'Orangeville Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('orillia-transit', 'Orillia Transit', 'Orillia Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('ottawa-river-transit', 'Ottawa River Transit', 'ORTC', 'CA', 'ON', 12, 'CAD', ARRAY['on_demand']),
  ('owen-sound-transit', 'Owen Sound Transit', 'Owen Sound Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('peterborough-transit', 'Peterborough Transit', 'Peterborough Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('port-hope-transit', 'Port Hope Transit', 'Port Hope Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('railway-city-transit', 'Railway City Transit', 'Railway City Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('sault-ste-marie-transit', 'Sault Ste. Marie Transit Services', 'Sault Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('simcoe-linx-transit', 'LINX Transit', 'Simcoe County LINX', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('stratford-transit', 'Stratford Transit', 'Stratford Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('tecumseh-transit', 'Tecumseh Transit', 'Tecumseh Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('thunder-bay-transit', 'Thunder Bay Transit', 'Thunder Bay Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('tillsonburg-transit', 'Tillsonburg Transit (T:GO)', 'T:GO', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('timmins-transit', 'Timmins Transit', 'Timmins Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('transit-windsor', 'Transit Windsor', 'Transit Windsor', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('wasaga-beach-transit', 'Wasaga Beach Transit', 'Wasaga Beach Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('woodstock-transit', 'Woodstock Transit', 'Woodstock Transit', 'CA', 'ON', 12, 'CAD', ARRAY['bus']),
  ('york-region-transit', 'York Region Transit', 'YRT', 'CA', 'ON', 12, 'CAD', ARRAY['bus','brt']),
  ('t3-transit', 'T3 Transit', 'T3 Transit', 'CA', 'PE', 12, 'CAD', ARRAY['bus']),
  ('baie-comeau-transit', 'Transport en commun de la Ville de Baie-Comeau', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('drummondville-transit', 'Service de transport en commun de Drummondville', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('exo', 'exo (Réseau de transport métropolitain)', 'exo', 'CA', 'QC', 12, 'CAD', ARRAY['commuter_rail','bus','on_demand','paratransit']),
  ('granby-transit', 'Transport urbain Granby', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('joliette-transit', 'Transport MRC de Joliette', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('mont-tremblant-transit', 'Transport en commun de la Ville de Mont-Tremblant', 'TCMT', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('pierre-de-saurel-transit', 'Société de transport collectif de Pierre-De Saurel', 'STC Pierre-De Saurel', 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('riviere-du-loup-transit', 'Transport Vas-Y inc. (MRC de Rivière-du-Loup)', 'Vas-Y', 'CA', 'QC', 12, 'CAD', ARRAY['on_demand']),
  ('rouyn-noranda-transit', 'Transport en commun de la Ville de Rouyn-Noranda', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('rtc-quebec', 'Réseau de transport de la Capitale', 'RTC', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('rtl-longueuil', 'Réseau de transport de Longueuil', 'RTL', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('saint-hyacinthe-transit', 'Transport collectif de la Ville de Saint-Hyacinthe', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('saint-jean-richelieu-transit', 'Transport en commun de la Ville de Saint-Jean-sur-Richelieu', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('shawinigan-transit', 'Régie de transport en commun de Shawinigan', 'RTCS', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('stl-laval', 'Société de transport de Laval', 'STL', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('stlevis', 'Société de transport de Lévis', 'STLévis', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('sto-gatineau', 'Société de transport de l''Outaouais', 'STO', 'CA', 'QC', 12, 'CAD', ARRAY['bus','brt']),
  ('str-rimouski', 'Société des transports de Rimouski', 'STR', 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('sts-saguenay', 'Société de transport du Saguenay', 'STS', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('sts-sherbrooke', 'Société de transport de Sherbrooke', 'STS', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('sttr-trois-rivieres', 'Société de transport de Trois-Rivières', 'STTR', 'CA', 'QC', 12, 'CAD', ARRAY['bus']),
  ('transcollines', 'Transcollines', 'Transcollines', 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('valleyfield-transit', 'Société de transport de Salaberry-de-Valleyfield', 'STSV', 'CA', 'QC', 12, 'CAD', ARRAY['bus','on_demand']),
  ('victoriaville-taxibus', 'TaxiBus de Victoriaville', NULL, 'CA', 'QC', 12, 'CAD', ARRAY['on_demand']),
  ('battlefords-transit', 'Battlefords Transit System', 'North Battleford Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus']),
  ('moose-jaw-transit', 'Moose Jaw Transit', 'Moose Jaw Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus']),
  ('prince-albert-transit', 'Prince Albert Transit', 'Prince Albert Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus']),
  ('regina-transit', 'Regina Transit', 'Regina Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus']),
  ('saskatoon-transit', 'Saskatoon Transit', 'Saskatoon Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus','on_demand']),
  ('swift-current-transit', 'Swift Transit', 'Swift Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus']),
  ('yorkton-transit', 'Yorkton Transit', 'Yorkton Transit', 'CA', 'SK', 12, 'CAD', ARRAY['bus']),
  ('whitehorse-transit', 'Whitehorse Transit', NULL, 'CA', 'YT', 12, 'CAD', ARRAY['bus','paratransit'])
ON CONFLICT (slug) DO NOTHING;

-- agency <-> mode links, resolved by slug/code (identity ids are not hardcoded).
INSERT INTO core.agency_modes (agency_id, mode_id, status)
SELECT a.id, m.id, 'active'
FROM core.agencies a
JOIN core.modes m ON true
WHERE (a.slug, m.code) IN (VALUES
  ('airdrie-transit', 'bus'),
  ('airdrie-transit', 'on_demand'),
  ('beaumont-transit', 'bus'),
  ('camrose-transit', 'bus'),
  ('cochrane-colt', 'bus'),
  ('cochrane-colt', 'on_demand'),
  ('cold-lake-transit', 'bus'),
  ('fort-saskatchewan-transit', 'bus'),
  ('grande-prairie-transit', 'bus'),
  ('grande-prairie-transit', 'on_demand'),
  ('hinton-transit', 'bus'),
  ('leduc-transit', 'bus'),
  ('leduc-transit', 'on_demand'),
  ('lethbridge-transit', 'bus'),
  ('medicine-hat-transit', 'bus'),
  ('medicine-hat-transit', 'on_demand'),
  ('okotoks-transit', 'bus'),
  ('okotoks-transit', 'on_demand'),
  ('red-deer-county-transit', 'bus'),
  ('red-deer-transit', 'bus'),
  ('roam-transit', 'bus'),
  ('spruce-grove-transit', 'bus'),
  ('spruce-grove-transit', 'on_demand'),
  ('st-albert-transit', 'bus'),
  ('strathcona-county-transit', 'bus'),
  ('strathcona-county-transit', 'on_demand'),
  ('whitecourt-transit', 'bus'),
  ('wood-buffalo-transit', 'bus'),
  ('wood-buffalo-transit', 'on_demand'),
  ('west-vancouver-blue-bus', 'bus'),
  ('brandon-transit', 'bus'),
  ('flin-flon-transit', 'bus'),
  ('selkirk-transit', 'bus'),
  ('winkler-transit', 'on_demand'),
  ('winnipeg-transit', 'bus'),
  ('winnipeg-transit', 'brt'),
  ('acadian-peninsula-flexi', 'bus'),
  ('bathurst-flexgo', 'on_demand'),
  ('codiac-transpo', 'bus'),
  ('edmundston-flexgo', 'bus'),
  ('edmundston-flexgo', 'on_demand'),
  ('fredericton-transit', 'bus'),
  ('miramichi-transit', 'bus'),
  ('saint-john-transit', 'bus'),
  ('corner-brook-transit', 'bus'),
  ('corner-brook-transit', 'on_demand'),
  ('happy-valley-goose-bay-transit', 'on_demand'),
  ('metrobus-st-johns', 'bus'),
  ('antigonish-transit', 'bus'),
  ('antigonish-transit', 'on_demand'),
  ('bayrides', 'on_demand'),
  ('bridgewater-transit', 'bus'),
  ('cape-breton-transit', 'bus'),
  ('east-hants-rider', 'on_demand'),
  ('halifax-transit', 'bus'),
  ('halifax-transit', 'ferry'),
  ('musgo-rider', 'on_demand'),
  ('pictou-county-transit', 'bus'),
  ('strait-area-transit', 'bus'),
  ('strait-area-transit', 'on_demand'),
  ('tidal-transit', 'bus'),
  ('yarmouth-transit', 'bus'),
  ('yellowknife-transit', 'bus'),
  ('yellowknife-transit', 'paratransit'),
  ('barrie-transit', 'bus'),
  ('belleville-transit', 'bus'),
  ('brampton-transit', 'bus'),
  ('brampton-transit', 'brt'),
  ('brantford-transit', 'bus'),
  ('brockville-transit', 'bus'),
  ('bwg-transit', 'on_demand'),
  ('chatham-kent-transit', 'bus'),
  ('cobourg-transit', 'bus'),
  ('cobourg-transit', 'on_demand'),
  ('collingwood-transit', 'bus'),
  ('cornwall-transit', 'bus'),
  ('durham-region-transit', 'bus'),
  ('durham-region-transit', 'on_demand'),
  ('elliot-lake-transit', 'bus'),
  ('grand-river-transit', 'bus'),
  ('grand-river-transit', 'light_rail'),
  ('greater-sudbury-transit', 'bus'),
  ('guelph-transit', 'bus'),
  ('hamilton-street-railway', 'bus'),
  ('huntsville-transit', 'bus'),
  ('kenora-transit', 'on_demand'),
  ('kingston-transit', 'bus'),
  ('leamington-transit', 'on_demand'),
  ('lindsay-transit', 'bus'),
  ('london-transit', 'bus'),
  ('midland-penetanguishene-transit', 'bus'),
  ('milton-transit', 'bus'),
  ('milton-transit', 'on_demand'),
  ('niagara-transit', 'bus'),
  ('north-bay-transit', 'bus'),
  ('oakville-transit', 'bus'),
  ('oakville-transit', 'on_demand'),
  ('orangeville-transit', 'bus'),
  ('orillia-transit', 'bus'),
  ('ottawa-river-transit', 'on_demand'),
  ('owen-sound-transit', 'bus'),
  ('peterborough-transit', 'bus'),
  ('port-hope-transit', 'bus'),
  ('railway-city-transit', 'bus'),
  ('sault-ste-marie-transit', 'bus'),
  ('simcoe-linx-transit', 'bus'),
  ('stratford-transit', 'bus'),
  ('tecumseh-transit', 'bus'),
  ('thunder-bay-transit', 'bus'),
  ('tillsonburg-transit', 'bus'),
  ('timmins-transit', 'bus'),
  ('transit-windsor', 'bus'),
  ('wasaga-beach-transit', 'bus'),
  ('woodstock-transit', 'bus'),
  ('york-region-transit', 'bus'),
  ('york-region-transit', 'brt'),
  ('t3-transit', 'bus'),
  ('baie-comeau-transit', 'bus'),
  ('drummondville-transit', 'bus'),
  ('drummondville-transit', 'on_demand'),
  ('exo', 'commuter_rail'),
  ('exo', 'bus'),
  ('exo', 'on_demand'),
  ('exo', 'paratransit'),
  ('granby-transit', 'bus'),
  ('granby-transit', 'on_demand'),
  ('joliette-transit', 'bus'),
  ('joliette-transit', 'on_demand'),
  ('mont-tremblant-transit', 'bus'),
  ('pierre-de-saurel-transit', 'bus'),
  ('pierre-de-saurel-transit', 'on_demand'),
  ('riviere-du-loup-transit', 'on_demand'),
  ('rouyn-noranda-transit', 'bus'),
  ('rtc-quebec', 'bus'),
  ('rtl-longueuil', 'bus'),
  ('saint-hyacinthe-transit', 'bus'),
  ('saint-jean-richelieu-transit', 'bus'),
  ('shawinigan-transit', 'bus'),
  ('stl-laval', 'bus'),
  ('stlevis', 'bus'),
  ('sto-gatineau', 'bus'),
  ('sto-gatineau', 'brt'),
  ('str-rimouski', 'bus'),
  ('str-rimouski', 'on_demand'),
  ('sts-saguenay', 'bus'),
  ('sts-sherbrooke', 'bus'),
  ('sttr-trois-rivieres', 'bus'),
  ('transcollines', 'bus'),
  ('transcollines', 'on_demand'),
  ('valleyfield-transit', 'bus'),
  ('valleyfield-transit', 'on_demand'),
  ('victoriaville-taxibus', 'on_demand'),
  ('battlefords-transit', 'bus'),
  ('moose-jaw-transit', 'bus'),
  ('prince-albert-transit', 'bus'),
  ('regina-transit', 'bus'),
  ('saskatoon-transit', 'bus'),
  ('saskatoon-transit', 'on_demand'),
  ('swift-current-transit', 'bus'),
  ('yorkton-transit', 'bus'),
  ('whitehorse-transit', 'bus'),
  ('whitehorse-transit', 'paratransit')
)
ON CONFLICT (agency_id, mode_id) DO NOTHING;
